safe: true
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'serve.sh', 'article.png', 'LICENSE', 'vendor']
baseurl: /paper-now-timetraveller/
imports:
    - https://peerj.github.io/research-article/research-article.html
collections:
    figures:
        output: true
        title: 'Figures'
    tables:
        output: true
        title: 'Tables'
    sections:
        output: true
